@echo off
echo Building frontend...
call npm run build
echo Clearing extension/dashboard...
rmdir /s /q "..\extension\dashboard" 2>nul
echo Copying...
mkdir "..\extension\dashboard" 2>nul
xcopy /e /y "dist\*" "..\extension\dashboard\"
echo Done.
